---
- name: Converge
  hosts: all
  become: true

  vars:
    # Role: yum_config_manager
    repositories:
      enabled:
        - rhui-REGION-rhel-server-rhscl
        - rhui-REGION-rhel-server-debug-rhscl

    # Role: mysql
    mysql_scl_package: rh-mariadb103
    mysql_use_scl: true
    mysql_databases:
      - name: example
    mysql_users:
      - name: jdoe
        password: password
        priv: "example.*:ALL"

  roles:
    - role: nycrecords.rhsm
    - role: ansible-role-mysql
